FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -e . && pip install --no-cache-dir bentoml
EXPOSE 3000
CMD ["bentoml", "serve", "inference_server.bento_service:AgroLidarService", "--host", "0.0.0.0", "--port", "3000"]
